### PR TITLE
Allow longer fingerprint

### PR DESCRIPTION
**Pull request by sashascurtu**
Change-Id: I89a64cd561d9915a8ef99d2aff6d8a2b22aedc46

### CODE REVIEW

**Comment by gotenksIN** [comment]
does any fingerprint get cut off? you are using redfin which is 65 rn, way under 120

**Comment by sashascurtu** [comment]
> does any fingerprint get cut off? you are using redfin which is 65 rn, way under 120

This value applies to all system props. My cam auxpackagelist is a bit longer than the limit. That's why i pr-ed this change.
error: vendor.camera.aux.packagelist cannot exceed 91 bytes: com.android.camera,org.codeaurora.snapcam,org.lineageos.snap,com.google.android.GoogleCamera (92)

**Comment by gotenksIN** [comment]
hm, can you fpush with commit message `build: tools: increase max length for properties`
current one is a bit misleading

**Comment by sashascurtu** [comment]
> hm, can you fpush with commit message `build: tools: increase max length for properties`
> current one is a bit misleading

sure

**Pull request merged**
